# Puppetfile for r10k modules

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'rbenv',
  :git => 'https://github.com/justindowning/puppet-rbenv'

mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat'

mod 'postgresql',
  :git => 'https://github.com/puppetlabs/puppetlabs-postgresql'

mod 'nginx',
  :git => 'https://github.com/jfryman/puppet-nginx'

mod 'nodejs',
  :git => 'https://github.com/puppet-community/puppet-nodejs'
